name: autobound
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
      - customtkinter==5.2.0
      - darkdetect==0.8.0 
      - imageio==2.31.1
      - imageio-ffmpeg==0.4.8
      - moviepy==1.0.3
      - numpy==1.25.0
      - opencv-python==4.7.0.72
      - pillow==9.5.0
      - proglog==0.1.10
      - requests==2.31.0
      - torch==1.13.1
      - torch-directml==0.1.13.1.dev230413
      - torchvision==0.14.1
      - tqdm==4.65.0
      - typing-extensions==4.6.3
      - urllib3==2.0.3
      - django>=4.2
      - djangorestframework>=3.14
      - django-environ>=0.11
      - psycopg2-binary>=2.9
      - django-storages[s3]>=1.14
      - boto3>=1.34
