# Generated by Django 6.0.3 on 2026-04-05 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='frame_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='videofile',
            name='frame_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
