# Generated by Django 6.0.3 on 2026-04-05 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0002_annotation_frame_number_videofile_frame_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='fps',
            field=models.FloatField(default=30.0),
        ),
    ]
