# Generated by Django 6.0.3 on 2026-04-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0005_add_export_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotation',
            name='track_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
